---

# - name: Install all required package
#   package:
#     name: "{{ lvm_packages }}"
#     state: present

# - name: Import volumegroups
#   vg_export_import:
#     vg: "{{ [item['name'] }}"
#     state: imported
#   failed_when: false
#   loop: "{{ lvm['vg'] }}"
#   when: item['import'] is defined and item['import'] | bool

- name: Create volumegroups
  community.general.lvg:
    vg: "{{ item['name'] }}"
    pvs: "{{ lookup('template', 'pvs.yml.j2') | from_yaml }}"
    pvresize: "{{ item['pvresize'] | default(false) }}"
  loop: "{{ lvm['vg'] }}"
  when:
    - item.when is undefined or vars[item.when] | bool

- name: Create logical volumes
  community.general.lvol:
    vg: "{{ item['vg'] }}"
    lv: "{{ item['name'] }}"
    size: "{{ item['size'] }}"
    resizefs: "{{ lvm_resizefs | default(True) }}"
    shrink: "{{ lvm_shrink | default(False) }}"
    opts: "{{ item['opts'] | default(omit) }}"
  loop: "{{ lvm['lv'] }}"
  when:
    - item.type is undefined
    - item.when is undefined or vars[item.when] | bool

- name: Create VDO logical volumes
  ansible.builtin.command:
    cmd: >-
      lvcreate
      --type vdo
      --name {{ item['name'] }}
      --vdopool {{ item.pool_name }}
      --size {{ item['size'] }}
      --virtualsize {{ item['virtualsize'] }}
      --deduplication {{ item['deduplication'] | default('y') }}
      --compression {{ item['compression'] | default('y') }}
      {{ item['vg'] }}
  when:
    - item.type == 'vdo'
    - item.name not in (ansible_facts.lvm.lvs | default({}))
  loop: "{{ lvm['lv'] }}"
  loop_control:
    label: "{{ item.name }}"

- name: Extend VDO logical size
  ansible.builtin.command:
    cmd: >-
      lvextend -L {{ item.virtualsize }} /dev/{{ item.vg }}/{{ item.name }}
  when:
    - item.type == 'vdo'
    - item.name in (ansible_facts.lvm.lvs | default({}))
    - item.virtualsize | regex_replace('G') | int > ansible_facts['lvm']['lvs'][item.name]['size_g'] | int
  loop: "{{ lvm['lv'] }}"
  loop_control:
    label: "{{ item.name }}"

- name: Extend VDO physical size
  ansible.builtin.command:
    cmd: >-
      lvextend -L {{ item.size }} {{ item.vg }}/{{ item.pool_name }}
  when:
    - item.type == 'vdo'
    - item.pool_name in (ansible_facts.lvm.lvs | default({}))
    - item.size | regex_replace('G') | int > ansible_facts['lvm']['lvs'][item.pool_name]['size_g'] | int
  loop: "{{ lvm['lv'] }}"
  loop_control:
    label: "{{ item.pool_name }}"

- name: Create filesystems
  community.general.filesystem:
    fstype: "{{ item['fstype'] }}"
    dev: "/dev/mapper/{{ item['vg'] + '-' + item['name'] }}"
    resizefs: "{{ lvm_resizefs | default(True) }}"
  loop: "{{ lvm['lv'] }}"
  when:
    - item.when is undefined or vars[item.when] | bool
    - item.fstype is defined and item.fstype is not search('^(raw|swap)$')

- name: Mount mountpoint
  ansible.posix.mount:
    path: "{{ item['mp'] }}"
    fstype: "{{ item['fstype'] }}"
    src: "/dev/mapper/{{ item['vg'] + '-' + item['name'] }}"
    state: mounted
  loop: "{{ lvm['lv'] }}"
  when:
    - item.when is undefined or vars[item.when] | bool
    - item['fstype'] is defined and item['fstype'] is not search('^(raw|swap)$')

- name: Set permissions & ownership
  ansible.builtin.file:
    path: "{{ item['mp'] }}"
    owner: "{{ item['owner'] | default('root') }}"
    group: "{{ item['group'] | default('root') }}"
    mode: "{{ item['mode'] | default('0755') }}"
    state: directory
  when:
    - item.when is undefined or vars[item.when] | bool
    - item['mp'] is defined
    - item['mp_change'] is undefined or item['mp_change'] | bool
  loop: "{{ lvm['lv'] }}"
