---

- name: Incude tasks 'scsi.yml'
  ansible.builtin.include_tasks: scsi.yml

- name: Include tasks 'lvm.yml'
  ansible.builtin.include_tasks: lvm.yml

- name: Include tasks 'swap.yml'
  ansible.builtin.include_tasks: swap.yml
